### ISSUE TITLE
Content missing on Impact page

### ISSUE THREAD

**Issue by Andrew-Dame** [international-child-art-foundation/icaf#10]
At the bottom of https://icaf.org/impact we provide a history of achievements. Photos or pdfs for some years (or part of year) are missing. We need them in a folder with subfolders for each relevant year. Could you please add this content (70Mb) > https://we.tl/t-sxtODCWW47

**Comment by Andrew-Dame** [comment]
@kojiro-soooo Are you available to take this one?

**Comment by kojiro-soooo** [comment]
@Andrew-Dame Yes, I can take a look here. This was among a few other updates that Ashfaq requested, but I can take this one after addressing some of the other minor updates.

**Comment by kojiro-soooo** [comment]
I've finished adding photos/pdfs to any achievements where there was content available, but some achievements still didn't have a corresponding photo/pdf. I've let Ashfaq know and I'm waiting to hear back on how he wants to proceed in case he has other files.
