### ISSUE TITLE
Update 'about us' page

### ISSUE THREAD

**Issue by YaosenTang** [international-child-art-foundation/icaf#59]
Please replace the text and image at https://icaf.org/about/about-us with the ones attached.

![About](https://github.com/international-child-art-foundation/icaf/assets/90784250/e73bcae8-994b-4b01-8a7c-68053d864ed5)
[ABOUT_07Oct23.docx](https://github.com/international-child-art-foundation/icaf/files/12850686/ABOUT_07Oct23.docx)

**Comment by 31Hemlock** [comment]
@YaosenTang Please change the image to the new one attached to this comment. It will need to be losslessly converted to webp.
![about-color-graded](https://github.com/international-child-art-foundation/icaf/assets/58008724/9a107510-f407-4ca3-a8a7-edd143d36ebe)
